#! /usr/bin/env bash

xhost +
docker run --rm -it -v ~/Downloads:/root/Downloads -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.mozilla/firefox/custom/user.js:/root/.mozilla/firefox/custom/user.js -e DISPLAY=$DISPLAY hackenfreude/firefox
xhost -
